---
openapi: 3.0.2
info:
  $ref: ./info/index.yaml
  version: "v1.3.1-feature-management-draft"
servers:
  - url: https://api.cujo.io/v1/
    description: ""
tags:
  - name: Feature Management API
    description:  |-
      Scope of Feature Management API is CUJO AI feature management, such as:
      * Device Intelligence
      * Advanced Security
      * Parental Control
      * Privacy

      General notes:
      * Initial version of this API is used for accounting-only purposes (not for controlling behavior of CPE itself).
      * Settings payload (set of properties) may differ depending on feature.
      * Full set of payload properties is expected for *update* requests. If property is omitted, default value is assumed.
      * Full set of payload properties is returned as response for both *get* and *update* requests.
      * Error codes are defined in general error codes section.

paths:
  /agents/{agentId}/features/device-intelligence:
    parameters:
      - name: agentId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Feature Management API
      summary: Get Device Intelligence settings
      description: Get Device Intelligence feature settings for specified agent
      operationId: GetDeviceIntelligence
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      refId: 7a42804e-3c57-4d49-9ba6-1253b11210ee
                    }
        404:
          description: Specified agent has no settings for device-intelligence feature defined
          content:
            application/json:
              schema:
                $ref: "/src/swagger.yaml#/components/schemas/ErrorResponse"
              examples:
                notFound:
                  value:
                    error: "Agent with id: {agentId} does not have device-intelligence settings defined"
      security:
        - AccessToken: []
    post:
      tags:
        - Feature Management API
      summary: Update Device Intelligence settings
      description: Update Device Intelligence feature settings for specified agent
      operationId: UpdateDeviceIntelligence
      requestBody:
        content:
          application/json:
            schema:
              $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsRequest"
            examples:
              example no 1:
                value:
                  {
                    enabled: true
                  }
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      refId: 1bbd5536-961a-4739-8123-ddfffd4a50c2
                    }
      security:
        - AccessToken: []
  /agents/{agentId}/features/advanced-security:
    parameters:
      - name: agentId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Feature Management API
      summary: Get Advanced Security settings
      description: Get Advanced Security feature settings for specified agent
      operationId: GetAdvanceSecurity
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/AdvancedSecuritySettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      listenOnly: false,
                      refId: d3fb877b-2b6b-4f5d-b16b-16d50165cc0e
                    }
        404:
          description: Specified agent has no settings for advanced-security feature defined
          content:
            application/json:
              schema:
                $ref: "/src/swagger.yaml#/components/schemas/ErrorResponse"
              examples:
                notFound:
                  value:
                    error: "Agent with id: {agentId} does not have advanced-security settings defined"
      security:
        - AccessToken: []
    post:
      tags:
        - Feature Management API
      summary: Update Advanced Security settings
      description: Update Advance Security feature settings for specified agent
      operationId: UpdateAdvanceSecurity
      requestBody:
        content:
          application/json:
            schema:
              $ref: "/src/swagger-feature-management.yaml#/components/AdvancedSecuritySettingsRequest"
            examples:
              example no 1:
                value:
                  {
                    enabled: true,
                    listenOnly: true
                  }
              example no 2:
                value:
                  {
                    enabled: true
                  }
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/AdvancedSecuritySettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      listenOnly: true,
                      refId: ac0af711-e431-4207-bd31-154acaeb451d
                    }
                example no 2:
                  value:
                    {
                      enabled: true,
                      listenOnly: false,
                      refId: b901efa8-408b-4c48-ae8d-a213aee5c0c3
                    }
      security:
        - AccessToken: []
  /agents/{agentId}/features/parental-control:
    parameters:
      - name: agentId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Feature Management API
      summary: Get Parental Control settings
      description: Get Parental Control feature settings for specified agent
      operationId: GetParentalControl
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      refId: 5482c8f5-e506-4d3e-89d6-9338ce4a50cc
                    }
        404:
          description: Specified agent has no settings for parental-control feature defined
          content:
            application/json:
              schema:
                $ref: "/src/swagger.yaml#/components/schemas/ErrorResponse"
              examples:
                notFound:
                  value:
                    error: "Agent with id: {agentId} does not have parental-control settings defined"
      security:
        - AccessToken: []
    post:
      tags:
        - Feature Management API
      summary: Update Parental Control settings
      description: Update Parental Control feature settings for specified agent
      operationId: UpdateParentalControl
      requestBody:
        content:
          application/json:
            schema:
              $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsRequest"
            examples:
              example no 1:
                value:
                  {
                    enabled: true
                  }
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      refId: bc102021-822b-460a-9776-fd46fe6c31f9
                    }
      security:
        - AccessToken: []
  /agents/{agentId}/features/privacy:
    parameters:
      - name: agentId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Feature Management API
      summary: Get Privacy settings
      description: Get Privacy feature settings for specified agent
      operationId: GetPrivacy
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      refId: ef74bc40-f781-4c62-b4cf-7e318be74b0e
                    }
        404:
          description: Specified agent has no settings for privacy feature defined
          content:
            application/json:
              schema:
                $ref: "/src/swagger.yaml#/components/schemas/ErrorResponse"
              examples:
                notFound:
                  value:
                    error: "Agent with id: {agentId} does not have privacy settings defined"

      security:
        - AccessToken: []
    post:
      tags:
        - Feature Management API
      summary: Update Privacy settings
      description: Update Privacy feature settings for specified agent
      operationId: UpdatePrivacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsRequest"
            examples:
              example no 1:
                value:
                  {
                    enabled: true
                  }
        required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "/src/swagger-feature-management.yaml#/components/DefaultSettingsResponse"
              examples:
                example no 1:
                  value:
                    {
                      enabled: true,
                      refId: 0269085f-99a8-40ed-a941-95b67a4322cb
                    }
      security:
        - AccessToken: []

components:
  DefaultSettingsRequest:
    title: Settings
    description: Feature settings
    required:
      - enabled

    type: object
    properties:
      enabled:
        type: boolean
        description: Is feature enabled
  DefaultSettingsResponse:
    title: Settings
    description: Feature settings
    type: object
    properties:
      enabled:
        type: boolean
        description: Is feature enabled
      refId:
        type: uuid
        description: Auto-generated unique request identifier, used for tracing
  AdvancedSecuritySettingsRequest:
    title: Settings
    description: Feature settings
    required:
      - enabled

    type: object
    properties:
      enabled:
        type: boolean
        description: Is feature enabled
      listenOnly:
        type: boolean
        default: false
        description: Does enabled feature operate in listen-only mode.
  AdvancedSecuritySettingsResponse:
    title: Settings
    description: Feature settings

    type: object
    properties:
      enabled:
        type: boolean
        description: Is feature enabled
      listenOnly:
        type: boolean
        description: Does enabled feature operate in listen-only mode.
      refId:
        type: uuid
        description: Auto-generated unique request identifier, used for tracing
  tags:
    - name: Feature Management